import type { Metadata } from "next";
import "./globals.css";
import {geistMono, geistSans} from "@/app/config/fonts";
import {Provider} from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Provider>
          {children}
      </Provider>
      </body>
    </html>
  );
}
